{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): ...working... failed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING conda.exceptions:print_unexpected_error_report(1251): KeyError('pkgs_dirs')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1129, in __call__\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "    exit_code = do_call(args, p)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 93, in do_call\n",
      "    return getattr(module, func_name)(args, parser)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\notices\\core.py\", line 72, in wrapper\n",
      "    return_value = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_update.py\", line 22, in execute\n",
      "    install(args, parser, 'update')\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 261, in install\n",
      "    unlink_link_transaction = solver.solve_for_transaction(\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 156, in solve_for_transaction\n",
      "    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 199, in solve_for_diff\n",
      "    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 304, in solve_final_state\n",
      "    ssc = self._collect_all_metadata(ssc)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n",
      "    return f(*args, **kwds)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 467, in _collect_all_metadata\n",
      "    index, r = self._prepare(prepared_specs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 1061, in _prepare\n",
      "    reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 301, in get_reduced_index\n",
      "    new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 115, in query_all\n",
      "    create_cache_dir()\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 737, in create_cache_dir\n",
      "    cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 158, in first_writable\n",
      "    pkgs_dirs = context.pkgs_dirs\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\base\\context.py\", line 555, in pkgs_dirs\n",
      "    fixed_dirs += user_data_dir(APP_NAME, APP_NAME),\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 67, in user_data_dir\n",
      "    path = os.path.join(_get_win_folder(const), appauthor, appname)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 265, in _get_win_folder_with_pywin32\n",
      "    from win32com.shell import shellcon, shell\n",
      "ImportError: DLL load failed while importing shell: 지정된 프로시저를 찾을 수 없습니다.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1249, in print_unexpected_error_report\n",
      "    message_builder.append(get_main_info_str(error_report['conda_info']))\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_info.py\", line 237, in get_main_info_str\n",
      "    info_dict['_' + key] = ('\\n' + 26 * ' ').join(info_dict[key])\n",
      "KeyError: 'pkgs_dirs'\n",
      "\n",
      "# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1129, in __call__\n",
      "        return func(*args, **kwargs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "        exit_code = do_call(args, p)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 93, in do_call\n",
      "        return getattr(module, func_name)(args, parser)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\notices\\core.py\", line 72, in wrapper\n",
      "        return_value = func(*args, **kwargs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_update.py\", line 22, in execute\n",
      "        install(args, parser, 'update')\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 261, in install\n",
      "        unlink_link_transaction = solver.solve_for_transaction(\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 156, in solve_for_transaction\n",
      "        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 199, in solve_for_diff\n",
      "        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 304, in solve_final_state\n",
      "        ssc = self._collect_all_metadata(ssc)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n",
      "        return f(*args, **kwds)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 467, in _collect_all_metadata\n",
      "        index, r = self._prepare(prepared_specs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 1061, in _prepare\n",
      "        reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 301, in get_reduced_index\n",
      "        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 115, in query_all\n",
      "        create_cache_dir()\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 737, in create_cache_dir\n",
      "        cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 158, in first_writable\n",
      "        pkgs_dirs = context.pkgs_dirs\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\base\\context.py\", line 555, in pkgs_dirs\n",
      "        fixed_dirs += user_data_dir(APP_NAME, APP_NAME),\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 67, in user_data_dir\n",
      "        path = os.path.join(_get_win_folder(const), appauthor, appname)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 265, in _get_win_folder_with_pywin32\n",
      "        from win32com.shell import shellcon, shell\n",
      "    ImportError: DLL load failed while importing shell: 지정된 프로시저를 찾을 수 없습니다.\n",
      "\n",
      "`$ c:\\Users\\qnwje\\anaconda3\\Scripts\\conda-script.py update conda`\n",
      "\n",
      "  environment variables:\n",
      "conda info could not be constructed.\n",
      "KeyError('pkgs_dirs')\n",
      "\n",
      "An unexpected error has occurred. Conda has prepared the above report.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pip in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (22.2.2)\n",
      "Collecting pip\n",
      "  Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: To modify pip, please run the following command:\n",
      "c:\\Users\\qnwje\\anaconda3\\python.exe -m pip install --upgrade pip\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: konlpy in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (0.6.0)\n",
      "Requirement already satisfied: numpy>=1.6 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from konlpy) (1.21.5)\n",
      "Requirement already satisfied: lxml>=4.1.0 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from konlpy) (4.9.1)\n",
      "Requirement already satisfied: JPype1>=0.7.0 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from konlpy) (1.4.1)\n",
      "Requirement already satisfied: packaging in c:\\users\\qnwje\\appdata\\roaming\\python\\python39\\site-packages (from JPype1>=0.7.0->konlpy) (21.3)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\\users\\qnwje\\appdata\\roaming\\python\\python39\\site-packages (from packaging->JPype1>=0.7.0->konlpy) (3.0.9)\n",
      "Requirement already satisfied: tweepy==3.10.0 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (3.10.0)\n",
      "Requirement already satisfied: requests[socks]>=2.11.1 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from tweepy==3.10.0) (2.28.1)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from tweepy==3.10.0) (1.3.1)\n",
      "Requirement already satisfied: six>=1.10.0 in c:\\users\\qnwje\\appdata\\roaming\\python\\python39\\site-packages (from tweepy==3.10.0) (1.16.0)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from requests-oauthlib>=0.7.0->tweepy==3.10.0) (3.2.2)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from requests[socks]>=2.11.1->tweepy==3.10.0) (1.26.11)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from requests[socks]>=2.11.1->tweepy==3.10.0) (2.0.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from requests[socks]>=2.11.1->tweepy==3.10.0) (2022.9.14)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from requests[socks]>=2.11.1->tweepy==3.10.0) (3.3)\n",
      "Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\\users\\qnwje\\anaconda3\\lib\\site-packages (from requests[socks]>=2.11.1->tweepy==3.10.0) (1.7.1)\n",
      "Collecting package metadata (current_repodata.json): ...working... failed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING conda.exceptions:print_unexpected_error_report(1251): KeyError('pkgs_dirs')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1129, in __call__\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "    exit_code = do_call(args, p)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 93, in do_call\n",
      "    return getattr(module, func_name)(args, parser)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\notices\\core.py\", line 72, in wrapper\n",
      "    return_value = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_install.py\", line 22, in execute\n",
      "    install(args, parser, 'install')\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 261, in install\n",
      "    unlink_link_transaction = solver.solve_for_transaction(\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 156, in solve_for_transaction\n",
      "    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 199, in solve_for_diff\n",
      "    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 304, in solve_final_state\n",
      "    ssc = self._collect_all_metadata(ssc)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n",
      "    return f(*args, **kwds)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 467, in _collect_all_metadata\n",
      "    index, r = self._prepare(prepared_specs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 1061, in _prepare\n",
      "    reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 301, in get_reduced_index\n",
      "    new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 115, in query_all\n",
      "    create_cache_dir()\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 737, in create_cache_dir\n",
      "    cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 158, in first_writable\n",
      "    pkgs_dirs = context.pkgs_dirs\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\base\\context.py\", line 555, in pkgs_dirs\n",
      "    fixed_dirs += user_data_dir(APP_NAME, APP_NAME),\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 67, in user_data_dir\n",
      "    path = os.path.join(_get_win_folder(const), appauthor, appname)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 265, in _get_win_folder_with_pywin32\n",
      "    from win32com.shell import shellcon, shell\n",
      "ImportError: DLL load failed while importing shell: 지정된 프로시저를 찾을 수 없습니다.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1249, in print_unexpected_error_report\n",
      "    message_builder.append(get_main_info_str(error_report['conda_info']))\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_info.py\", line 237, in get_main_info_str\n",
      "    info_dict['_' + key] = ('\\n' + 26 * ' ').join(info_dict[key])\n",
      "KeyError: 'pkgs_dirs'\n",
      "\n",
      "# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1129, in __call__\n",
      "        return func(*args, **kwargs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "        exit_code = do_call(args, p)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 93, in do_call\n",
      "        return getattr(module, func_name)(args, parser)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\notices\\core.py\", line 72, in wrapper\n",
      "        return_value = func(*args, **kwargs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_install.py\", line 22, in execute\n",
      "        install(args, parser, 'install')\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 261, in install\n",
      "        unlink_link_transaction = solver.solve_for_transaction(\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 156, in solve_for_transaction\n",
      "        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 199, in solve_for_diff\n",
      "        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 304, in solve_final_state\n",
      "        ssc = self._collect_all_metadata(ssc)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n",
      "        return f(*args, **kwds)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 467, in _collect_all_metadata\n",
      "        index, r = self._prepare(prepared_specs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 1061, in _prepare\n",
      "        reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 301, in get_reduced_index\n",
      "        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 115, in query_all\n",
      "        create_cache_dir()\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 737, in create_cache_dir\n",
      "        cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 158, in first_writable\n",
      "        pkgs_dirs = context.pkgs_dirs\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\base\\context.py\", line 555, in pkgs_dirs\n",
      "        fixed_dirs += user_data_dir(APP_NAME, APP_NAME),\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 67, in user_data_dir\n",
      "        path = os.path.join(_get_win_folder(const), appauthor, appname)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 265, in _get_win_folder_with_pywin32\n",
      "        from win32com.shell import shellcon, shell\n",
      "    ImportError: DLL load failed while importing shell: 지정된 프로시저를 찾을 수 없습니다.\n",
      "\n",
      "`$ c:\\Users\\qnwje\\anaconda3\\Scripts\\conda-script.py install -y -c conda-forge jpype==1.0.2`\n",
      "\n",
      "  environment variables:\n",
      "conda info could not be constructed.\n",
      "KeyError('pkgs_dirs')\n",
      "\n",
      "An unexpected error has occurred. Conda has prepared the above report.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): ...working... failed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING conda.exceptions:print_unexpected_error_report(1251): KeyError('pkgs_dirs')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1129, in __call__\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "    exit_code = do_call(args, p)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 93, in do_call\n",
      "    return getattr(module, func_name)(args, parser)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\notices\\core.py\", line 72, in wrapper\n",
      "    return_value = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_install.py\", line 22, in execute\n",
      "    install(args, parser, 'install')\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 261, in install\n",
      "    unlink_link_transaction = solver.solve_for_transaction(\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 156, in solve_for_transaction\n",
      "    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 199, in solve_for_diff\n",
      "    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 304, in solve_final_state\n",
      "    ssc = self._collect_all_metadata(ssc)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n",
      "    return f(*args, **kwds)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 467, in _collect_all_metadata\n",
      "    index, r = self._prepare(prepared_specs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 1061, in _prepare\n",
      "    reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 301, in get_reduced_index\n",
      "    new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 115, in query_all\n",
      "    create_cache_dir()\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 737, in create_cache_dir\n",
      "    cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 158, in first_writable\n",
      "    pkgs_dirs = context.pkgs_dirs\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\base\\context.py\", line 555, in pkgs_dirs\n",
      "    fixed_dirs += user_data_dir(APP_NAME, APP_NAME),\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 67, in user_data_dir\n",
      "    path = os.path.join(_get_win_folder(const), appauthor, appname)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 265, in _get_win_folder_with_pywin32\n",
      "    from win32com.shell import shellcon, shell\n",
      "ImportError: DLL load failed while importing shell: 지정된 프로시저를 찾을 수 없습니다.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1249, in print_unexpected_error_report\n",
      "    message_builder.append(get_main_info_str(error_report['conda_info']))\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_info.py\", line 237, in get_main_info_str\n",
      "    info_dict['_' + key] = ('\\n' + 26 * ' ').join(info_dict[key])\n",
      "KeyError: 'pkgs_dirs'\n",
      "\n",
      "# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1129, in __call__\n",
      "        return func(*args, **kwargs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "        exit_code = do_call(args, p)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 93, in do_call\n",
      "        return getattr(module, func_name)(args, parser)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\notices\\core.py\", line 72, in wrapper\n",
      "        return_value = func(*args, **kwargs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_install.py\", line 22, in execute\n",
      "        install(args, parser, 'install')\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 261, in install\n",
      "        unlink_link_transaction = solver.solve_for_transaction(\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 156, in solve_for_transaction\n",
      "        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 199, in solve_for_diff\n",
      "        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 304, in solve_final_state\n",
      "        ssc = self._collect_all_metadata(ssc)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n",
      "        return f(*args, **kwds)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 467, in _collect_all_metadata\n",
      "        index, r = self._prepare(prepared_specs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 1061, in _prepare\n",
      "        reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 301, in get_reduced_index\n",
      "        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 115, in query_all\n",
      "        create_cache_dir()\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 737, in create_cache_dir\n",
      "        cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 158, in first_writable\n",
      "        pkgs_dirs = context.pkgs_dirs\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\base\\context.py\", line 555, in pkgs_dirs\n",
      "        fixed_dirs += user_data_dir(APP_NAME, APP_NAME),\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 67, in user_data_dir\n",
      "        path = os.path.join(_get_win_folder(const), appauthor, appname)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 265, in _get_win_folder_with_pywin32\n",
      "        from win32com.shell import shellcon, shell\n",
      "    ImportError: DLL load failed while importing shell: 지정된 프로시저를 찾을 수 없습니다.\n",
      "\n",
      "`$ c:\\Users\\qnwje\\anaconda3\\Scripts\\conda-script.py install -y -c conda-forge wordcloud`\n",
      "\n",
      "  environment variables:\n",
      "conda info could not be constructed.\n",
      "KeyError('pkgs_dirs')\n",
      "\n",
      "An unexpected error has occurred. Conda has prepared the above report.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): ...working... failed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING conda.exceptions:print_unexpected_error_report(1251): KeyError('pkgs_dirs')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1129, in __call__\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "    exit_code = do_call(args, p)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 93, in do_call\n",
      "    return getattr(module, func_name)(args, parser)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\notices\\core.py\", line 72, in wrapper\n",
      "    return_value = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_install.py\", line 22, in execute\n",
      "    install(args, parser, 'install')\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 261, in install\n",
      "    unlink_link_transaction = solver.solve_for_transaction(\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 156, in solve_for_transaction\n",
      "    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 199, in solve_for_diff\n",
      "    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 304, in solve_final_state\n",
      "    ssc = self._collect_all_metadata(ssc)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n",
      "    return f(*args, **kwds)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 467, in _collect_all_metadata\n",
      "    index, r = self._prepare(prepared_specs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 1061, in _prepare\n",
      "    reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 301, in get_reduced_index\n",
      "    new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 115, in query_all\n",
      "    create_cache_dir()\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 737, in create_cache_dir\n",
      "    cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 158, in first_writable\n",
      "    pkgs_dirs = context.pkgs_dirs\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\base\\context.py\", line 555, in pkgs_dirs\n",
      "    fixed_dirs += user_data_dir(APP_NAME, APP_NAME),\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 67, in user_data_dir\n",
      "    path = os.path.join(_get_win_folder(const), appauthor, appname)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 265, in _get_win_folder_with_pywin32\n",
      "    from win32com.shell import shellcon, shell\n",
      "ImportError: DLL load failed while importing shell: 지정된 프로시저를 찾을 수 없습니다.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1249, in print_unexpected_error_report\n",
      "    message_builder.append(get_main_info_str(error_report['conda_info']))\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_info.py\", line 237, in get_main_info_str\n",
      "    info_dict['_' + key] = ('\\n' + 26 * ' ').join(info_dict[key])\n",
      "KeyError: 'pkgs_dirs'\n",
      "\n",
      "# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1129, in __call__\n",
      "        return func(*args, **kwargs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "        exit_code = do_call(args, p)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 93, in do_call\n",
      "        return getattr(module, func_name)(args, parser)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\notices\\core.py\", line 72, in wrapper\n",
      "        return_value = func(*args, **kwargs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_install.py\", line 22, in execute\n",
      "        install(args, parser, 'install')\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 261, in install\n",
      "        unlink_link_transaction = solver.solve_for_transaction(\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 156, in solve_for_transaction\n",
      "        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 199, in solve_for_diff\n",
      "        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 304, in solve_final_state\n",
      "        ssc = self._collect_all_metadata(ssc)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n",
      "        return f(*args, **kwds)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 467, in _collect_all_metadata\n",
      "        index, r = self._prepare(prepared_specs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 1061, in _prepare\n",
      "        reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 301, in get_reduced_index\n",
      "        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 115, in query_all\n",
      "        create_cache_dir()\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 737, in create_cache_dir\n",
      "        cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 158, in first_writable\n",
      "        pkgs_dirs = context.pkgs_dirs\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\base\\context.py\", line 555, in pkgs_dirs\n",
      "        fixed_dirs += user_data_dir(APP_NAME, APP_NAME),\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 67, in user_data_dir\n",
      "        path = os.path.join(_get_win_folder(const), appauthor, appname)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 265, in _get_win_folder_with_pywin32\n",
      "        from win32com.shell import shellcon, shell\n",
      "    ImportError: DLL load failed while importing shell: 지정된 프로시저를 찾을 수 없습니다.\n",
      "\n",
      "`$ c:\\Users\\qnwje\\anaconda3\\Scripts\\conda-script.py install -y nltk`\n",
      "\n",
      "  environment variables:\n",
      "conda info could not be constructed.\n",
      "KeyError('pkgs_dirs')\n",
      "\n",
      "An unexpected error has occurred. Conda has prepared the above report.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): ...working... failed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING conda.exceptions:print_unexpected_error_report(1251): KeyError('pkgs_dirs')\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1129, in __call__\n",
      "    return func(*args, **kwargs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "    exit_code = do_call(args, p)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 93, in do_call\n",
      "    return getattr(module, func_name)(args, parser)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\notices\\core.py\", line 72, in wrapper\n",
      "    return_value = func(*args, **kwargs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_install.py\", line 22, in execute\n",
      "    install(args, parser, 'install')\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 261, in install\n",
      "    unlink_link_transaction = solver.solve_for_transaction(\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 156, in solve_for_transaction\n",
      "    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 199, in solve_for_diff\n",
      "    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 304, in solve_final_state\n",
      "    ssc = self._collect_all_metadata(ssc)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n",
      "    return f(*args, **kwds)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 467, in _collect_all_metadata\n",
      "    index, r = self._prepare(prepared_specs)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 1061, in _prepare\n",
      "    reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 301, in get_reduced_index\n",
      "    new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 115, in query_all\n",
      "    create_cache_dir()\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 737, in create_cache_dir\n",
      "    cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 158, in first_writable\n",
      "    pkgs_dirs = context.pkgs_dirs\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\base\\context.py\", line 555, in pkgs_dirs\n",
      "    fixed_dirs += user_data_dir(APP_NAME, APP_NAME),\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 67, in user_data_dir\n",
      "    path = os.path.join(_get_win_folder(const), appauthor, appname)\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 265, in _get_win_folder_with_pywin32\n",
      "    from win32com.shell import shellcon, shell\n",
      "ImportError: DLL load failed while importing shell: 지정된 프로시저를 찾을 수 없습니다.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1249, in print_unexpected_error_report\n",
      "    message_builder.append(get_main_info_str(error_report['conda_info']))\n",
      "  File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_info.py\", line 237, in get_main_info_str\n",
      "    info_dict['_' + key] = ('\\n' + 26 * ' ').join(info_dict[key])\n",
      "KeyError: 'pkgs_dirs'\n",
      "\n",
      "# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "    Traceback (most recent call last):\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1129, in __call__\n",
      "        return func(*args, **kwargs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "        exit_code = do_call(args, p)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 93, in do_call\n",
      "        return getattr(module, func_name)(args, parser)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\notices\\core.py\", line 72, in wrapper\n",
      "        return_value = func(*args, **kwargs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\main_install.py\", line 22, in execute\n",
      "        install(args, parser, 'install')\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 261, in install\n",
      "        unlink_link_transaction = solver.solve_for_transaction(\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 156, in solve_for_transaction\n",
      "        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 199, in solve_for_diff\n",
      "        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 304, in solve_final_state\n",
      "        ssc = self._collect_all_metadata(ssc)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\common\\io.py\", line 86, in decorated\n",
      "        return f(*args, **kwds)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 467, in _collect_all_metadata\n",
      "        index, r = self._prepare(prepared_specs)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\solve.py\", line 1061, in _prepare\n",
      "        reduced_index = get_reduced_index(self.prefix, self.channels,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 301, in get_reduced_index\n",
      "        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 115, in query_all\n",
      "        create_cache_dir()\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\subdir_data.py\", line 737, in create_cache_dir\n",
      "        cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 158, in first_writable\n",
      "        pkgs_dirs = context.pkgs_dirs\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\base\\context.py\", line 555, in pkgs_dirs\n",
      "        fixed_dirs += user_data_dir(APP_NAME, APP_NAME),\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 67, in user_data_dir\n",
      "        path = os.path.join(_get_win_folder(const), appauthor, appname)\n",
      "      File \"c:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\conda\\_vendor\\appdirs.py\", line 265, in _get_win_folder_with_pywin32\n",
      "        from win32com.shell import shellcon, shell\n",
      "    ImportError: DLL load failed while importing shell: 지정된 프로시저를 찾을 수 없습니다.\n",
      "\n",
      "`$ c:\\Users\\qnwje\\anaconda3\\Scripts\\conda-script.py install -y scikit-learn`\n",
      "\n",
      "  environment variables:\n",
      "conda info could not be constructed.\n",
      "KeyError('pkgs_dirs')\n",
      "\n",
      "An unexpected error has occurred. Conda has prepared the above report.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!conda update conda\n",
    "!pip install --upgrade pip\n",
    "!pip install konlpy\n",
    "!pip install tweepy==3.10.0\n",
    "!conda install -y -c conda-forge jpype1==1.0.2\n",
    "!conda install -y -c conda-forge wordcloud\n",
    "!conda install -y nltk\n",
    "!conda install -y scikit-learn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import nltk\n",
    "\n",
    "nltk.download()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'1.4.1'"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import jpype\n",
    "\n",
    "jpype.__version__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "ename": "JVMNotFoundException",
     "evalue": "No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mJVMNotFoundException\u001b[0m                      Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\qnwje\\OneDrive\\바탕 화면\\zerobase\\제로베이스_강의\\머신러닝\\08.NLP.ipynb Cell 4\u001b[0m line \u001b[0;36m3\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/qnwje/OneDrive/%EB%B0%94%ED%83%95%20%ED%99%94%EB%A9%B4/zerobase/%EC%A0%9C%EB%A1%9C%EB%B2%A0%EC%9D%B4%EC%8A%A4_%EA%B0%95%EC%9D%98/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D/08.NLP.ipynb#W3sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mkonlpy\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtag\u001b[39;00m \u001b[39mimport\u001b[39;00m Okt\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/qnwje/OneDrive/%EB%B0%94%ED%83%95%20%ED%99%94%EB%A9%B4/zerobase/%EC%A0%9C%EB%A1%9C%EB%B2%A0%EC%9D%B4%EC%8A%A4_%EA%B0%95%EC%9D%98/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D/08.NLP.ipynb#W3sZmlsZQ%3D%3D?line=2'>3</a>\u001b[0m t \u001b[39m=\u001b[39m Okt()\n",
      "File \u001b[1;32mc:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\konlpy\\tag\\_okt.py:51\u001b[0m, in \u001b[0;36mOkt.__init__\u001b[1;34m(self, jvmpath, max_heap_size)\u001b[0m\n\u001b[0;32m     49\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m__init__\u001b[39m(\u001b[39mself\u001b[39m, jvmpath\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, max_heap_size\u001b[39m=\u001b[39m\u001b[39m1024\u001b[39m):\n\u001b[0;32m     50\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m jpype\u001b[39m.\u001b[39misJVMStarted():\n\u001b[1;32m---> 51\u001b[0m         jvm\u001b[39m.\u001b[39;49minit_jvm(jvmpath, max_heap_size)\n\u001b[0;32m     53\u001b[0m     oktJavaPackage \u001b[39m=\u001b[39m jpype\u001b[39m.\u001b[39mJPackage(\u001b[39m'\u001b[39m\u001b[39mkr.lucypark.okt\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m     54\u001b[0m     OktInterfaceJavaClass \u001b[39m=\u001b[39m oktJavaPackage\u001b[39m.\u001b[39mOktInterface\n",
      "File \u001b[1;32mc:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\konlpy\\jvm.py:55\u001b[0m, in \u001b[0;36minit_jvm\u001b[1;34m(jvmpath, max_heap_size)\u001b[0m\n\u001b[0;32m     52\u001b[0m args \u001b[39m=\u001b[39m [javadir, os\u001b[39m.\u001b[39msep]\n\u001b[0;32m     53\u001b[0m classpath \u001b[39m=\u001b[39m [f\u001b[39m.\u001b[39mformat(\u001b[39m*\u001b[39margs) \u001b[39mfor\u001b[39;00m f \u001b[39min\u001b[39;00m folder_suffix]\n\u001b[1;32m---> 55\u001b[0m jvmpath \u001b[39m=\u001b[39m jvmpath \u001b[39mor\u001b[39;00m jpype\u001b[39m.\u001b[39;49mgetDefaultJVMPath()\n\u001b[0;32m     57\u001b[0m \u001b[39m# NOTE: Temporary patch for Issue #76. Erase when possible.\u001b[39;00m\n\u001b[0;32m     58\u001b[0m \u001b[39mif\u001b[39;00m sys\u001b[39m.\u001b[39mplatform \u001b[39m==\u001b[39m \u001b[39m'\u001b[39m\u001b[39mdarwin\u001b[39m\u001b[39m'\u001b[39m\\\n\u001b[0;32m     59\u001b[0m         \u001b[39mand\u001b[39;00m jvmpath\u001b[39m.\u001b[39mfind(\u001b[39m'\u001b[39m\u001b[39m1.8.0\u001b[39m\u001b[39m'\u001b[39m) \u001b[39m>\u001b[39m \u001b[39m0\u001b[39m\\\n\u001b[0;32m     60\u001b[0m         \u001b[39mand\u001b[39;00m jvmpath\u001b[39m.\u001b[39mendswith(\u001b[39m'\u001b[39m\u001b[39mlibjvm.dylib\u001b[39m\u001b[39m'\u001b[39m):\n",
      "File \u001b[1;32mc:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\jpype\\_jvmfinder.py:74\u001b[0m, in \u001b[0;36mgetDefaultJVMPath\u001b[1;34m()\u001b[0m\n\u001b[0;32m     72\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m     73\u001b[0m     finder \u001b[39m=\u001b[39m LinuxJVMFinder()\n\u001b[1;32m---> 74\u001b[0m \u001b[39mreturn\u001b[39;00m finder\u001b[39m.\u001b[39;49mget_jvm_path()\n",
      "File \u001b[1;32mc:\\Users\\qnwje\\anaconda3\\lib\\site-packages\\jpype\\_jvmfinder.py:212\u001b[0m, in \u001b[0;36mJVMFinder.get_jvm_path\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    210\u001b[0m \u001b[39mif\u001b[39;00m jvm_notsupport_ext \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m    211\u001b[0m     \u001b[39mraise\u001b[39;00m jvm_notsupport_ext\n\u001b[1;32m--> 212\u001b[0m \u001b[39mraise\u001b[39;00m JVMNotFoundException(\u001b[39m\"\u001b[39m\u001b[39mNo JVM shared library file (\u001b[39m\u001b[39m{0}\u001b[39;00m\u001b[39m) \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m    213\u001b[0m                            \u001b[39m\"\u001b[39m\u001b[39mfound. Try setting up the JAVA_HOME \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m    214\u001b[0m                            \u001b[39m\"\u001b[39m\u001b[39menvironment variable properly.\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m    215\u001b[0m                            \u001b[39m.\u001b[39mformat(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_libfile))\n",
      "\u001b[1;31mJVMNotFoundException\u001b[0m: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly."
     ]
    }
   ],
   "source": [
    "from konlpy.tag import Okt\n",
    "\n",
    "t = Okt()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'3.10.0'"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import tweepy\n",
    "\n",
    "tweepy.__version__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
